# Example runtime settings for Longport Quant
ENVIRONMENT = "development"
TRADING_TIMEZONE = "Asia/Hong_Kong"
LONGPORT_API_BASE = "https://openapi.longportapp.com"
LONGPORT_WS_URL = "wss://openapi-quote.longportapp.com/v1/quote"
LONGPORT_TRADE_WS_URL = "wss://openapi-trade.longportapp.com/v1/trade"
LONGPORT_APP_KEY = "your-app-key"
LONGPORT_APP_SECRET = "your-app-secret"
LONGPORT_ACCESS_TOKEN = "optional-access-token"
LONGPORT_REGION = "hk"
DATABASE_DSN = "postgresql+asyncpg://user:password@localhost:5432/longport"
REDIS_URL = "redis://localhost:6379/0"
WATCHLIST_PATH = "configs/watchlist.yml"
STRATEGY_MODULES = ["longport_quant.strategies.watchlist_auto.AutoTradeStrategy"]
LOG_LEVEL = "INFO"
LOG_PATH = "logs/app.log"
HEALTHCHECK_PORT = 8080
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/xxx/yyy/zzz"
